### ISSUE TITLE
Update di bootstrap-italia@1.2.10

### ISSUE THREAD

**Issue by enricobasso** [francescozaia/hugo-theme-bootstrap-italia#1]
Ho provato ad aggiornare css e js del tema portando bootstrap-italia alla 1.2.10, a quanto pare però sembra ci sia qualche problema nel caricamento dei font.

`(index):220 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff2 net::ERR_ABORTED 404 (Not Found)   

(index):220 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff2 net::ERR_ABORTED 404 (Not Found)   
(index):220 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff2 net::ERR_ABORTED 404 (Not Found)   
(index):220 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff2 net::ERR_ABORTED 404 (Not Found)   
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
(index):1 GET http://localhost:1313/bootstrap-italia/dist/fonts/Lora/Lora-Regular.woff net::ERR_ABORTED 404 (Not Found)
android-chrome-192x192.png:1 GET http://localhost:1313/bootstrap-italia/docs/assets/img/favicons/android-chrome-192x192.png 404 (Not Found)
:1313/#:1 Error while trying to use the following icon from the Manifest: http://localhost:1313/bootstrap-italia/docs/assets/img/favicons/android-chrome-192x192.png (Download error or resource isn't a valid image)
`

**Comment by francescozaia** [comment]
Sì, dalla versione 0.x è cambiata la modalità di gestione dei font, non più richiamati da Google Fonts nel rispetto della privacy degli utilizzatori. Vedo di aggiornarlo al più presto, ti taggo qui appena fatto.

**Comment by francescozaia** [comment]
...ma siccome mi sono preso quarto d'ora, ho sistemato al volo. @enricobasso ora dovrebbe essere a posto, utilizzando il solito readme (o aggiornando la cartella `hugo-theme-bootstrap-italia` sulla tua installazione locale di Hugo), dovrebbe funzionare.
