### ISSUE TITLE
load jquery eariler

### ISSUE THREAD

**Issue by simevo** [francescozaia/hugo-theme-bootstrap-italia#13]
In this theme the boostrap-italia javascript bundle is loaded in the scripts partial (`layouts/partials/site-scripts.html`) after the footer

As we need jquery earlier, we tried to load it in the head (`layouts/partials/site-head.html`), but that causes a javascript error in the console because the bundle executes commands that require the DOM to be loaded outside an on document loaded function; more precisely, in the chromium console:
```
bootstrap-italia.bundle.js:28998 Uncaught TypeError: Cannot read property 'appendChild' of null
    at bootstrap-italia.bundle.js:28998
```
error is here:
```
document.body.appendChild(styleNode)
```

Possible solutions:
1. we use the unbundled js libraries and load just jquery in the head and leave boostrap-italia after the footer
2. or you fix the boostrap-italia javascript bundle so that it can be included in the head

what do you suggest ?

**Comment by francescozaia** [comment]
It's not good practice to put any javascript in the head section (without deferring it), as it blocks page rendering during its fetch/execution phase.
So, I would suggest you execute any javascript manipulation after the page is loaded.
